steps:
  - name: node
    entrypoint: npm
    args: ["install"]
  - name: node
    entrypoint: npm
    args: ["run", "build"]
    secretEnv:
      ["SERVICE_ACCOUNT_PROD", "REVALIDATE_SECRET", "STRIPE_TEST_KEY_SECRET"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    secretEnv:
      ["SERVICE_ACCOUNT_PROD", "REVALIDATE_SECRET", "STRIPE_TEST_KEY_SECRET"]
options:
  logging: CLOUD_LOGGING_ONLY
availableSecrets:
  secretManager:
    - versionName: projects/202331496756/secrets/FIREBASE_SERVICE_ACCOUNT_PROD/versions/latest
      env: "SERVICE_ACCOUNT_PROD"
    - versionName: projects/202331496756/secrets/NEXT_REVALIDATE_SECRET/versions/latest
      env: "REVALIDATE_SECRET"
    - versionName: projects/202331496756/secrets/STRIPE_TEST_SECRET/versions/latest
      env: "STRIPE_TEST_KEY_SECRET"
